server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: darmoz-auth

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexora}
    username: ${SPRING_DATASOURCE_USERNAME:nexora}
    password: ${SPRING_DATASOURCE_PASSWORD:nexora}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: auth_flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:./keys-dev/private_key.pem}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:./keys-dev/public_key.pem}
  access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS:720}
  refresh-token-ttl-days: ${JWT_REFRESH_TOKEN_TTL_DAYS:30}
  issuer: ${JWT_ISSUER:darmoz-auth}

darmoz:
  mail:
    base-url: ${DARMOZ_MAIL_BASE_URL:http://localhost:8081/darmoz-mail}
    client-id: ${DARMOZ_MAIL_CLIENT_ID:5e6a88c0-01bb-455b-963a-81965e3a7b6d}

email-verification:
  code-ttl-minutes: ${EMAIL_VERIFICATION_CODE_TTL_MINUTES:15}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.darmoz.auth: INFO
